covr support
Appsilon/rhino pull request #431
Opened 2023-01-25 06:11 UTC by radbasa

## Changes

Two functions.

* `covr_r()`
* `covr_report()`

Requires [`Appsilon/covr@klmr-box-support`](https://github.com/Appsilon/covr)

## Take Note

With `box` an exported variable and a module can have the same name. For example,

```
# example_name.R

#' @export
example_name <- "example string"      # variable
```

```
# test-example_name.R
box::use(
  app/example_name[example_name]
)

testthat("", {
  example_name
})
```

With `testthat` this is not a problem. But, this will throw an error inside `covr`. Inside a `covr` run, the call to `example_name` returns the `box` module, not the variable object. A solution is to use aliases in the unit test:

```
# test-example_name.R
box::use(
  app/example_name[en = example_name]
)

testthat("", {
  en
})
```

Closes #99 

## How to use

Inside a rhino app

1. Remove existing installed `covr` package.
2. Install Appsilon version of `covr`, `devtools::install_github("Appsilon/covr@klmr-box-support")` or `remotes::install_github("Appsilon/covr@klmr-box-support")`
3. `rhino::covr_r()` to run a coverage test
4. `rhino::covr_report()` to produce an HTML report

2023-01-25 07:50 UTC, jakubnowicki commented
Since this PR depends on the change done to `covr`, we need to wait for it to be accepted and included in CRAN release.

2023-01-25 07:52 UTC, jakubnowicki commented on DESCRIPTION
> +Version: 1.3.0.1
```suggestion
Version: 1.3.0.9000
```

2023-01-25 10:26 UTC, radbasa commented
Added parameters to `rhino::covr_r()`
```
#' @param test_files Character vector of test files with code to test the functions. Defaults to
#'   all test files in `tests/testthat` with the `test-<name>.R` filename pattern.
#' @param line_exclusions passed to `covr::file_coverage`
#' @param function_exclusions passed to `covr::file_coverage`
```

2024-02-08 04:14 UTC, radbasa commented
@Johan-rosa Any comments on the covr-related functions?

2024-02-19 19:23 UTC, johan-wbd commented
> @Johan-rosa Any comments on the covr-related functions? Message in private if necessary.

We tested these changes and everything is working as expected.

2024-02-19 19:25 UTC, Johan-rosa commented
> @Johan-rosa Any comments on the covr-related functions? Message in private if necessary.

We're using these changes and everything is working as expected. Great job!

2024-03-07 08:50 UTC, jakubsob commented
Hello 👋 

I just gave it a shot, and it looks like those commands don't handle snapshot tests, I get plenty of those messages:
```r
Can't compare snapshot to reference when testing interactively.
ℹ Run `devtools::test()` or `testthat::test_file()` to see changes.
New path: /var/folders/vk/yrfnlfbs4dq06zwj3rqg5h0m0000gn/T//RtmpZI1MKq/file27e160337ac1.csv
```
I'm not sure if `covr` is the reason for that or the way test code is run by the rhino command, just letting you know. But it'd be nice if it handled snapshot tests. 🙏 

After the commands stops running I don't get any output:
```r
coverage <- rhino::covr_r()
r$> coverage

r$> str(coverage)
 list()
 - attr(*, "class")= chr "coverage"

r$> print(coverage)
NULL
```
Do you have an idea why this could happen?

2026-05-21 07:54 UTC, jakubnowicki requested changes
Works really well, we are almost there. Please check my comments.

2026-05-21 07:54 UTC, jakubnowicki commented on tests/e2e/app-files/main.R
Please add missing line at the end.

2026-05-21 07:54 UTC, jakubnowicki commented on tests/testthat/helpers/test-hello.R
It would be good to cover two additional cases:
1. Function imported with `module$function` (so a more basic one).
2. Private function (with the second pattern from `box` [guide](https://klmr.me/box/articles/testing.html#test-interfaces-not-implementation-details)).
I have run some manual tests, and it works, but it is important to have the test case to monitor it.

2026-06-05 09:12 UTC, radbasa commented on tests/testthat/helpers/test-hello.R
Both implemented in `say_hello_module.R` and `test-say_hello_module.R`.

Available in both unit tests and e2e tests.

2026-06-08 07:30 UTC, jakubnowicki approved these changes
:tada:

2026-06-08 07:30 UTC, merged